name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

variables:
  "System.PreferGit": true
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://toxdev.visualstudio.com/tox/_build/results?buildId=$(Build.BuildId)"
  PYTEST_ADDOPTS: "-v -v -ra --showlocals"
  GIT_BRANCH: $[ coalesce(variables['System.PullRequest.SourceBranch'], variables['Build.SourceBranchName'], 'not-found') ]
  GIT_COMMIT_SHA: $[ coalesce(variables['System.PullRequest.SourceCommitId'], variables['Build.SourceVersion'], 'not-found') ]

trigger:
  batch: true
  branches:
    include:
    - master
    - refs/tags/*
  paths:
    exclude:
    - readthedocs.yml
    - LICENSE
    - HOWTORELEASE.rst
    - CONTRIBUTORS
    - CONTRIBUTING.rst
    - CODE_OF_CONDUCT.md
    - .gitignore
    - .github/*
    - tasks/*

jobs:
- template: azure-run-tox-env.yml
  parameters: {tox: py27, python: 2.7, os: windows, uniq: a}
- template: azure-run-tox-env.yml
  parameters: {tox: py27, python: 2.7, os: windows, uniq: b}
- template: azure-run-tox-env.yml
  parameters: {tox: py27, python: 2.7, os: windows, uniq: c}
- template: azure-run-tox-env.yml
  parameters: {tox: py27, python: 2.7, os: windows, uniq: d}
- template: azure-run-tox-env.yml
  parameters: {tox: py27, python: 2.7, os: windows, uniq: e}
